#!/bin/sh
# Copyright (c) 2016 Heikki Hokkanen <hoxu at users.sf.net>
set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 <command> [parameters]"
    exit 1
fi

OBJECT_STORE="$(git rev-parse --git-dir)/gig/objects"

if [ "$1" = "add" ]; then
    sha1=$(git hash-object -w "$2")
    sha256=$(sha256sum "$2" |awk '{print $1}')
    git update-ref refs/gig/$sha256 $sha1

    mkdir -p "$OBJECT_STORE"
    cp "$2" "$OBJECT_STORE/$sha256"
    rm -f "$2"
    ln -s "$OBJECT_STORE/$sha256" "$2"
elif [ "$1" = "push" ]; then
    file="$2"
    [ -L "$file" ] || (echo "Can only push gig files"; exit 1)

    sha256=$(basename $(readlink "$file"))

    git push origin refs/gig/$sha256:refs/gig/$sha256
else
    echo "Unknown command: $1" >&2
    exit 1
fi
