#!/bin/sh
# Copyright (c) 2016 Heikki Hokkanen <hoxu at users.sf.net>
set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 <command> [parameters]"
    exit 1
fi

OBJECT_STORE="$(git rev-parse --git-dir)/big/objects"

fetch_file()
{
    [ -L "$1" ] || (echo "Can only fetch git-big files"; exit 1)
    local sha256
    sha256=$(basename $(readlink "$1"))

    git fetch origin refs/big/$sha256:refs/big/$sha256
    git show refs/big/$sha256 > "$OBJECT_STORE/$sha256"
    chmod -w "$OBJECT_STORE/$sha256"
}

fetch_dir()
{
    find "$1" -lname '*.git/big/objects*' |while read -r filename; do
        fetch_file "$filename"
    done
}

push_file()
{
    [ -L "$1" ] || (echo "$0: not object link: $1"; exit 1)

    local sha256
    sha256=$(basename $(readlink "$1"))

    git push origin refs/big/$sha256:refs/big/$sha256
}

push_dir()
{
    local dir="$1"
    find "$dir" -lname '*.git/big/objects/*' |while read -r filename; do
        push_file "$filename"
    done
}

if [ "$1" = "add" ]; then
    sha1=$(git hash-object -w "$2")
    sha256=$(sha256sum "$2" |awk '{print $1}')
    git update-ref refs/big/$sha256 $sha1

    mkdir -p "$OBJECT_STORE"
    mv "$2" "$OBJECT_STORE/$sha256"
    chmod -w "$OBJECT_STORE/$sha256"
    ln -s "$OBJECT_STORE/$sha256" "$2"
    git add "$2"
elif [ "$1" = "drop" ]; then
    sha256=$(basename $(readlink "$2"))
    rm -f "$OBJECT_STORE/$sha256"
    git update-ref -d refs/big/$sha256
elif [ "$1" = "fetch" ]; then
    shift
    for i in "${@:-.}"; do
        if [ -L "$i" ]; then
            fetch_file "$i"
        elif [ -d "$i" ]; then
            fetch_dir "$i"
        else
            echo "$0: can not fetch: $i"
            exit 1
        fi
    done
elif [ "$1" = "push" ]; then
    shift
    for i in "${@:-.}"; do
        if [ -f "$i" ]; then
            push_file "$i"
        elif [ -d "$i" ]; then
            push_dir "$i"
        else
            echo "$0: can not push: $i"
            exit 1
        fi
    done
elif [ "$1" = "unlock" ]; then
    [ -L "$2" ] || (echo "Can only unlock git-big files"; exit 1)

    sha256=$(basename $(readlink "$2"))
    rm -f "$2"
    cp --reflink=auto --sparse=auto $OBJECT_STORE/$sha256 "$2"
    chmod +w "$2"
else
    echo "Unknown command: $1" >&2
    exit 1
fi
