#!/bin/sh
set -u

binary=$(readlink -f "./gig")

setUp()
{
    REPO=$(mktemp -d)
    git init "$REPO"
    REMOTE=$(mktemp -d)
    git init --bare "$REMOTE"
    cd "$REPO"
}

tearDown()
{
    cd -
    rm -rf "$REPO" "$REMOTE"
}

testAddFile()
{
    echo foo > file.txt
    $binary add file.txt
    sha256=$(sha256sum file.txt |awk '{print $1}')

    git show $(git hash-object --stdin < file.txt) > /dev/null || fail "git object does not exist"

    [ -f "$(git rev-parse --git-dir)/gig/objects/$sha256" ] || fail "gig object does not exist"

    [ -L file.txt ] || fail "file must be a symlink"
    assertEquals "$(readlink file.txt)" ".git/gig/objects/$sha256"
}

. shunit2
